use_frameworks!

target 'BeautyEditor_Example' do
  pod 'BeautyEditor', :path => '../'

  target 'BeautyEditor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
